import { db } from '@/db';
import { vehicles } from '@/db/schema';

async function main() {
    const sampleVehicles = [
        {
            partnerId: 3,
            vehicleType: 'bike',
            brand: 'Hero',
            model: 'Splendor',
            registrationNumber: 'BR01AB1234',
            year: 2022,
            color: 'Black',
            imageUrl: null,
            hourlyRate: 50,
            dailyRate: 400,
            monthlyRate: 8000,
            status: 'available',
            location: 'Patna',
            gpsEnabled: true,
            lastServiceDate: new Date('2024-11-15').toISOString(),
            createdAt: new Date('2024-10-01').toISOString(),
        },
        {
            partnerId: 3,
            vehicleType: 'scooter',
            brand: 'Honda',
            model: 'Activa',
            registrationNumber: 'KA02CD5678',
            year: 2023,
            color: 'Red',
            imageUrl: null,
            hourlyRate: 60,
            dailyRate: 500,
            monthlyRate: 10000,
            status: 'available',
            location: 'Bengaluru',
            gpsEnabled: true,
            lastServiceDate: new Date('2024-11-20').toISOString(),
            createdAt: new Date('2024-10-05').toISOString(),
        },
        {
            partnerId: 3,
            vehicleType: 'electric',
            brand: 'TVS',
            model: 'iQube',
            registrationNumber: 'DL03EF9012',
            year: 2023,
            color: 'Blue',
            imageUrl: null,
            hourlyRate: 80,
            dailyRate: 700,
            monthlyRate: 15000,
            status: 'available',
            location: 'Delhi',
            gpsEnabled: true,
            lastServiceDate: new Date('2024-11-25').toISOString(),
            createdAt: new Date('2024-10-10').toISOString(),
        },
        {
            partnerId: 3,
            vehicleType: 'bike',
            brand: 'Bajaj',
            model: 'Pulsar',
            registrationNumber: 'BR04GH3456',
            year: 2021,
            color: 'Black',
            imageUrl: null,
            hourlyRate: 70,
            dailyRate: 600,
            monthlyRate: 12000,
            status: 'booked',
            location: 'Patna',
            gpsEnabled: true,
            lastServiceDate: new Date('2024-11-10').toISOString(),
            createdAt: new Date('2024-10-15').toISOString(),
        },
        {
            partnerId: 3,
            vehicleType: 'scooter',
            brand: 'Suzuki',
            model: 'Access',
            registrationNumber: 'KA05IJ7890',
            year: 2022,
            color: 'White',
            imageUrl: null,
            hourlyRate: 55,
            dailyRate: 450,
            monthlyRate: 9000,
            status: 'available',
            location: 'Bengaluru',
            gpsEnabled: true,
            lastServiceDate: new Date('2024-11-18').toISOString(),
            createdAt: new Date('2024-10-20').toISOString(),
        },
        {
            partnerId: 4,
            vehicleType: 'electric',
            brand: 'Ather',
            model: '450X',
            registrationNumber: 'DL06KL1234',
            year: 2023,
            color: 'Grey',
            imageUrl: null,
            hourlyRate: 90,
            dailyRate: 800,
            monthlyRate: 18000,
            status: 'maintenance',
            location: 'Delhi',
            gpsEnabled: true,
            lastServiceDate: null,
            createdAt: new Date('2024-10-25').toISOString(),
        },
        {
            partnerId: 4,
            vehicleType: 'bike',
            brand: 'Royal Enfield',
            model: 'Classic 350',
            registrationNumber: 'BR07MN5678',
            year: 2022,
            color: 'Brown',
            imageUrl: null,
            hourlyRate: 100,
            dailyRate: 900,
            monthlyRate: 20000,
            status: 'available',
            location: 'Patna',
            gpsEnabled: true,
            lastServiceDate: new Date('2024-11-12').toISOString(),
            createdAt: new Date('2024-11-01').toISOString(),
        },
        {
            partnerId: 4,
            vehicleType: 'scooter',
            brand: 'Yamaha',
            model: 'Fascino',
            registrationNumber: 'KA08OP9012',
            year: 2023,
            color: 'Pink',
            imageUrl: null,
            hourlyRate: 65,
            dailyRate: 550,
            monthlyRate: 11000,
            status: 'available',
            location: 'Bengaluru',
            gpsEnabled: true,
            lastServiceDate: new Date('2024-11-22').toISOString(),
            createdAt: new Date('2024-11-05').toISOString(),
        },
        {
            partnerId: 4,
            vehicleType: 'electric',
            brand: 'OLA',
            model: 'S1 Pro',
            registrationNumber: 'DL09QR3456',
            year: 2023,
            color: 'Black',
            imageUrl: null,
            hourlyRate: 85,
            dailyRate: 750,
            monthlyRate: 16000,
            status: 'available',
            location: 'Delhi',
            gpsEnabled: true,
            lastServiceDate: new Date('2024-11-28').toISOString(),
            createdAt: new Date('2024-11-10').toISOString(),
        },
        {
            partnerId: 4,
            vehicleType: 'bike',
            brand: 'Honda',
            model: 'CB Shine',
            registrationNumber: 'BR10ST7890',
            year: 2021,
            color: 'Blue',
            imageUrl: null,
            hourlyRate: 60,
            dailyRate: 500,
            monthlyRate: 10000,
            status: 'available',
            location: 'Patna',
            gpsEnabled: true,
            lastServiceDate: new Date('2024-11-05').toISOString(),
            createdAt: new Date('2024-11-15').toISOString(),
        },
    ];

    await db.insert(vehicles).values(sampleVehicles);
    
    console.log('✅ Vehicles seeder completed successfully');
}

main().catch((error) => {
    console.error('❌ Seeder failed:', error);
});